import { v4 as uuidv4 } from "uuid"
export const data = [
     {
          id: uuidv4(),
          name: "Nguyễn Văn Hương",
          employeeCode: "NV001",
          avatar: "/assets/images/user/user-1.png",
          groupEmployee: "Full-time",
          timeCheckIn: "8h15",
          timeCheckOut: "14h15",
          timeWork: "4h00",
          timePlan: "8h00",
          percent: 50,
          branch: "Chi nhánh miền Bắc",
          flag: "",
          map: "Toàn nhà UDIC, số 27 Huynh Thúc Kháng, Phường Láng Hạ, Quận Đống Đa, Hà Nội",
          createAt: "2021-10-20"
     },
     {
          id: uuidv4(),
          name: "Hoàng Thu Quỳnh",
          employeeCode: "NV002",
          avatar: "/assets/images/user/user-2.jpg",
          groupEmployee: "Part-time",
          timeCheckIn: "08h15",
          timeCheckOut: "14h15",
          timeWork: "4h00",
          timePlan: "4h00",
          percent: 100,
          branch: "Headquarter",
          flag: "",
          map: "Toàn nhà UDIC, số 27 Huynh Thúc Kháng, Phường Láng Hạ, Quận Đống Đa, Hà Nội",
          createAt: "2021-10-20"
     },
     {
          id: uuidv4(),
          name: "Nguyễn Vân Anh",
          employeeCode: "NV003",
          avatar: "/assets/images/user/user-2.jpg",
          groupEmployee: "Part-time",
          timeCheckIn: "08h15",
          timeCheckOut: "14h15",
          timeWork: "3h40",
          timePlan: "4h00",
          percent: 80,
          branch: "Headquarter",
          flag: "",
          map: "Toàn nhà UDIC, số 27 Huynh Thúc Kháng, Phường Láng Hạ, Quận Đống Đa, Hà Nội",
          createAt: "2021-10-20"
     },
     {
          id: uuidv4(),
          name: "Hà Anh Tuấn",
          employeeCode: "NV004",
          avatar: "/assets/images/user/user-1.png",
          groupEmployee: "Full-time",
          timeCheckIn: "08h15",
          timeCheckOut: "",
          timeWork: "4h30",
          timePlan: "8h00",
          percent: 60,
          branch: "Chi nhánh miền Bắc",
          flag: "",
          map: "Toàn nhà UDIC, số 27 Huynh Thúc Kháng, Phường Láng Hạ, Quận Đống Đa, Hà Nội",
          createAt: "2021-10-20"
     },
     {
          id: uuidv4(),
          name: "Vũ Phương Linh",
          employeeCode: "NV005",
          avatar: "/assets/images/user/user-2.jpg",
          groupEmployee: "Full-time",
          timeCheckIn: "08h15",
          timeCheckOut: "14h15",
          timeWork: "4h30",
          timePlan: "8h00",
          percent: 60,
          branch: "Chi nhánh miền Bắc",
          flag: "",
          map: "Toàn nhà UDIC, số 27 Huynh Thúc Kháng, Phường Láng Hạ, Quận Đống Đa, Hà Nội",
          createAt: "2021-10-20"
     }
]